/* ESTE SCRIPT CREA LAS TABLAS DE LA BASE DE DATOS
 * BASE DE DATOS EN MODELO RELACIONAL
 * AUTOR: JOSE PEÑA #11-10775 Y DANIELA SOCAS #11-10979
 */



CREATE TABLE COMPETENCIA (
	NOMBRE 				VARCHAR(40),
	TROFEO				VARCHAR(40)

);

CREATE TABLE LIGA (
	C_NOMBRE			VARCHAR(40)
);

CREATE TABLE COPA (
	C_NOMBRE 			VARCHAR(40) 
);

CREATE TABLE ORGANIZADOR (
	C_NOMBRE			VARCHAR(40),
	ORGANIZADOR 		VARCHAR(40)
);

CREATE TABLE TEMPORADA (
	AÑO					INTEGER,
	C_NOMBRE			VARCHAR(40)
);

CREATE TABLE EQUIPO(
	NOMBRE				VARCHAR(40),
	FUNDACION			TIMESTAMP,
	PAIS				VARCHAR(20),
	CIUDAD				VARCHAR(20),
	CAPACIDAD_ESTADIO	INTEGER,
	NOMBRE_ESTADIO		VARCHAR(40),
	P_COMPETENCIA		VARCHAR(40)
);

CREATE TABLE PARTIDO (
	FECHA				DATE,
	ASISTENCIA			INTEGER,
	MARCADOR			POINT,
	DURACION			INTEGER,
	LOCAL				VARCHAR(40),
	VISITANTE			VARCHAR(40),
	C_NOMBRE			VARCHAR(40),
	J_TEMPORADA			INTEGER,
	TC_NOMBRE			VARCHAR(40)
);

CREATE TABLE JUGADOR(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER,
	NACIMIENTO			TIMESTAMP,
	PIE_HABIL			VARCHAR(9),
	ESTATURA			REAL,
	PESO				REAL,
	CJ_EQUIPO			VARCHAR(40),
	CJ_CLAUSULA_RECE	INTEGER,
	CJ_SALARIO			INTEGER,
	CJ_FINALIZACION		DATE,
	CJ_INICIO 			DATE
);

CREATE TABLE J_NACIONALIDAD (
	FIFA_ID				INTEGER,
	NACIONALIDAD 		VARCHAR(40)
);

CREATE TABLE ARBITRO (
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER
);

CREATE TABLE A_NACIONALIDAD (
	FIFA_ID				INTEGER,
	NACIONALIDAD 		VARCHAR(40)
);

CREATE TABLE AMONESTA (
	MIN 				NUMERIC(2,0),
	AMARILLA			BOOLEAN,
	ROJA				BOOLEAN,
	A_JUGADOR			INTEGER,
	A_PARTIDO 			DATE,
	A_ARBITRO			INTEGER,
	LOCAL				VARCHAR(40),
	VISITANTE			VARCHAR(40)
);

CREATE TABLE GOL(
	MIN					NUMERIC(2,0),
	TIPO 				VARCHAR(13),
	EN_PARTIDO 			DATE,
	ASISTE				INTEGER NULL,
	ANOTA 				INTEGER,
	LOCAL				VARCHAR(40),
	VISITANTE 			VARCHAR(40)
);

CREATE TABLE TECNICO(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER,
	CT_EQUIPO			VARCHAR(40),
	CT_FINALIZACION		DATE,
	CT_INICIO 			DATE
);

CREATE TABLE SE_ANOTA (
	A_PARTIDO 			DATE,
	A_MIN				NUMERIC(2,0),
	P_LOCAL				VARCHAR(40),
	P_VISITANTE			VARCHAR(40),
	G_LOCAL				VARCHAR(40),
	G_VISITANTE			VARCHAR(40)
);

CREATE TABLE CONVOCADO (
	C_JUGADOR			INTEGER,
	C_PARTIDO			DATE, 
	MIN_ENTRA			INTEGER NULL,
	MIN_SALE			INTEGER NULL,
	POSICION			VARCHAR(24) NULL,
	LOCAL				VARCHAR(40),
	VISITANTE 			VARCHAR(40)
);

CREATE TABLE PERTENECE_A_LA (
	C_NOMBRE			VARCHAR(40),
	PARTIDO 			DATE,
	JORNADA				INTEGER NULL,
	FASE				VARCHAR(17) NULL,
	LOCAL				VARCHAR(40),
	VISITANTE 			VARCHAR(40)
);
 
CREATE TABLE COMPITE_EN (
	C_NOMBRE			VARCHAR(40),
	E_NOMBRE			VARCHAR(40)
);