/* ESTE SCRIPT ELIMINA LAS TABLAS DE LA BASE DE DATOS
 * BASE DE DATOS EN MODELO RELACIONAL
 * AUTOR: JOSE PEÑA #11-10775 Y DANIELA SOCAS #11-10979
 */

DROP TABLE PERTENECE_A_LA;
DROP TABLE P_COMPETENCIA;
DROP TABLE COMPITE_EN;
DROP TABLE CONVOCADO;
DROP TABLE SE_ANOTA;
DROP TABLE TECNICO;
DROP TABLE GOL;
DROP TABLE AMONESTA;
DROP TABLE A_NACIONALIDAD;
DROP TABLE ARBITRO;
DROP TABLE J_NACIONALIDAD;
DROP TABLE JUGADOR;
DROP TABLE PARTIDO;
DROP TABLE EQUIPO;
DROP TABLE ORGANIZADOR;
DROP TABLE TEMPORADA;
DROP TABLE LIGA;
DROP TABLE COPA;
DROP TABLE COMPETENCIA;
