DROP TABLE EQUIPO;

CREATE TABLE EQUIPO(
	NOMBRE				VARCHAR(40) CONSTRAINT PK_EQUIPO PRIMARY KEY,
	FUNDACION			TIMESTAMP,
	PAIS				VARCHAR(20),
	CIUDAD				VARCHAR(20),
	CAPACIDAD_ESTADIO	INTEGER,
	NOMBRE_ESTADIO		VARCHAR(40),
	P_COMPETENCIA		VARCHAR(40) CONSTRAINT FK_EQUIPO_COMPETENCIA 
									REFERENCES COMPETENCIA
);

CREATE TABLE TECNICO(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER CONSTRAINT PK_TECNICO PRIMARY KEY,
	CT_EQUIPO			VARCHAR(40)	CONSTRAINT FK_TECNICO_EQUIPO
									REFERENCES EQUIPO,
	CT_FINALIZACION		TIMESTAMP,
	CT_INICIO 			TIMESTAMP
);

CREATE TABLE JUGADOR(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER	CONSTRAINT PK_JUGADOR PRIMARY KEY,
	NACIMIENTO			TIMESTAMP,
	PIE_HABIL			VARCHAR(9) CONSTRAINT DOM_JUGADOR_PIE_HABIL CHECK
						(PIE_HABIL IN ('IZQUIERDO, DERECHO')),
	ESTATURA			REAL,
	PESO				REAL,
	CJ_EQUIPO			VARCHAR(40) CONSTRAINT FK_JUGADOR_TECNICO
									REFERENCES EQUIPO,
	CJ_CLAUSULA_RECE	INTEGER,
	CJ_SALARIO			INTEGER,
	CJ_FINALIZACION		TIMESTAMP,
	CJ_INICIO 			TIMESTAMP
	);

CREATE TABLE J_NACIONALIDAD (
	FIFA_ID				INTEGER CONSTRAINT FK_A_NACIONALIDAD_JUGADOR
								REFERENCES JUGADOR,
	NACIONALIDAD 		VARCHAR(40) CONSTRAINT PK_A_NACIONALIDAD PRIMARY KEY,
);

CREATE TABLE GOL(
	MIN					NUMERIC(2,0) CONSTRAINT PK_GOL PRIMARY KEY,
	TIPO 				VARCHAR(13) CONSTRAINT DOM_GOL_TIPO CHECK
						(TIPO IN ('TIRO LIBRE', 'PENAL', 'AUTOGOL', 'CABEZASO', 
							'PIE IZQUIERDO', 'PIE DERECHO')),
	EN_PARTIDO 			TIMESTAMP CONSTRAINT FK_GOL_SE_ANOTA
								  REFERENCES SE_ANOTA,
	ASISTE				INTEGER CONSTRAINT FK_GOL_JUGADOR
								REFERENCES JUGADOR,
	ANOTA 				INTEGER	CONSTRAINT FK_GOL_JUGADOR
								REFERENCES JUGADOR
);

CREATE TABLE SE_ANOTA (
	A_PARTIDO 			DATE CONSTRAINT FK_SE_ANOTA_PARTIDO
							REFERENCES PARTIDO,
	A_MIN				NUMERIC(2,0) CONSTRAINT FK_SE_ANOTA_GOL
								  	REFERENCES GOL
);

CREATE TABLE CONVOCADO (
	C_JUGADOR			INTEGER CONSTRAINT FK_CONVOCADO_JUGADOR
								REFERENCES JUGADOR,
	C_PARTIDO			DATE CONSTRAINT FK_CONVOCADO_PARTIDO,
	POSICION			VARCHAR(24) CONSTRAINT DOM_CONVOCADO_POSICION
						(POSICION IN ('DELANTERO PUNTA', 'DELANTERO IZQUIERDO', 
						'DELANTERO DERECHO', 'EXTREMO IZQUIERDO', 'EXTREMO DERECHO',
						'MEDIO CENTRO OFENSIVO', 'VOLANTE IZQUIERDO', 'VOLANTE DERECHO',
						'MEDIO CENTRO DEFENSIVO', 'MEDIO IZQUIERDO DEFENSIVO',
						'MEDIO DERECHO DEFENSIVO', 'LATERAL IZQUIERDO', 'LATERAL DERECHO',
						'DEFENSA MEDIO', 'PORTERO')),
	MIN_ENTRA			INTEGER,
	MIN_SALE			INTEGER
);

CREATE TABLE PARTIDO (
	FECHA				DATE CONSTRAINT PK_PARTIDO PRIMARY KEY,
	ASISTENCIA			INTEGER,
	MARCADOR			POINT,
	DURACION			INTEGER,
	LOCAL				VARCHAR(40) CONSTRAINT FK_PARTIDO_EQUIPO
								REFERENCES EQUIPO,
	VISITANTE			VARCHAR(40) CONSTRAINT FK_PARTIDO_EQUIPO
								REFERENCES EQUIPO,
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_PARTIDO_COMPETENCIA,
	J_TEMPORADA			INTEGER CONSTRAINT FK_PARTIDO_TEMPORADA
);

CREATE TABLE AMONESTA (
	MIN 				NUMERIC(2,0),
	AMARILLA			BOOLEAN,
	ROJO				BOOLEAN,
	A_JUGADOR			INTEGER CONSTRAINT FK_AMONESTA_JUGADOR
								REFERENCES JUGADOR,
	A_PARTIDO 			DATE CONSTRAINT FK_AMONESTA_PARTIDO
							  REFERENCES PARTIDO,
	A_ARBITRO			INTEGER CONSTRAINT FK_AMONESTA_ARBITRO,
);


CREATE TABLE ARBITRO (
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER CONSTRAINT PK_ARBITRO PRIMARY KEY
);

CREATE TABLE A_NACIONALIDAD (
	FIFA_ID				INTEGER CONSTRAINT FK_A_NACIONALIDAD_ARBITRO
								REFERENCES ARBITRO,
	NACIONALIDAD 		VARCHAR(40) CONSTRAINT PK_A_NACIONALIDAD PRIMARY KEY,
);

CREATE TABLE COMPETENCIA (
	NOMBRE 				VARCHAR(40) CONSTRAINT PK_COMPETENCIA PRIMARY KEY,
	TROFEO				VARCHAR(40)

);

CREATE TABLE ORGANIZADOR (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_ORGANIZADOR_COMPETENCIA
									REFERENCES COMPETENCIA,
	ORGANIZADOR 		VARCHAR(40) CONSTRAINT PK_ORGANIZADOR PRIMARY KEY
);

CREATE TABLE LIGA (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_LIGA_COMPETENCIA
									REFERENCES COMPETENCIA
);

CREATE TABLE COPA (
	C_NOMBRE 			VARCHAR(40) CONSTRAINT FK_COPA_COMPETENCIA
									REFERENCES COMPETENCIA
);

CREATE TABLE PERTENECE_A_LA (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_PERTENECE_COMPETENCIA
									REFERENCES COMPETENCIA,
	PARTIDO 			DATE CONSTRAINT FK_PERTENECE_PARTIDO
								REFERENCES PARTIDO,
	JORNADA				INTEGER,
	FASE				VARCHAR() CONSTRAINT DOM_PERTENECE_FASE
						(FASE IN ('FASE ELIMNATORIA', '32AVOS DE FINAL','16AVO DE FINAL', 
							'8AVO DE FINAL', '4TOS DE FINAL', 'SEMI-FINAL', 'FINAL'))
);

