DROP TABLE EQUIPO;

CREATE TABLE EQUIPO(
	NOMBRE				VARCHAR(40) CONSTRAINT PK_EQUIPO PRIMARY KEY,
	FUNDACION			TIMESTAMP,
	PAIS				VARCHAR(20),
	CIUDAD				VARCHAR(20),
	CAPACIDAD_ESTADIO	INTEGER,
	NOMBRE_ESTADIO		VARCHAR(40),
	P_COMPETENCIA		VARCHAR(40) CONSTRAINT FK_EQUIPO_COMPETENCIA 
									REFERENCES COMPETENCIA
);

CREATE TABLE TECNICO(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER CONSTRAINT PK_TECNICO PRIMARY KEY,
	CT_EQUIPO			VARCHAR(40)	CONSTRAINT FK_TECNICO_EQUIPO
									REFERENCES EQUIPO,
	CT_FINALIZACION		TIMESTAMP,
	CT_INICIO 			TIMESTAMP
);

CREATE TABLE JUGADOR(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER	CONSTRAINT PK_JUGADOR PRIMARY KEY,
	NACIMIENTO			TIMESTAMP,
	PIE_HABIL			VARCHAR(9) CONSTRAINT DOM_JUGADOR_PIE_HABIL CHECK
						(PIE_HABIL IN ('IZQUIERDO, DERECHO')),
	ESTATURA			REAL,
	PESO				REAL,
	CJ_EQUIPO			VARCHAR(40) CONSTRAINT FK_JUGADOR_TECNICO
									REFERENCES EQUIPO,
	CJ_CLAUSULA_RECE	INTEGER,
	CJ_SALARIO			INTEGER,
	CJ_FINALIZACION		TIMESTAMP,
	CJ_INICIO 			TIMESTAMP
	);
CREATE TABLE GOL(
	MIN					NUMERIC(2,0) CONSTRAINT PK_GOL PRIMARY KEY,
	TIPO 				VARCHAR(13) CONSTRAINT DOM_GOL_TIPO CHECK
						(TIPO IN ('TIRO LIBRE', 'PENAL', 'AUTOGOL', 'CABEZASO', 
							'PIE IZQUIERDO', 'PIE DERECHO')),
	EN_PARTIDO 			TIMESTAMP CONSTRAINT FK_GOL_SE_ANOTA
								  REFERENCES SE_ANOTA,
	ASISTE				INTEGER CONSTRAINT FK_GOL_JUGADOR
								REFERENCES JUGADOR,
	ANOTA 				INTEGER	CONSTRAINT FK_GOL_JUGADOR
								REFERENCES JUGADOR
);

CREATE TABLE SE_ANOTA (
	A_PARTIDO 			TIMESTAMP CONSTRAINT FK_SE_ANOTA_PARTIDO
								  REFERENCES PARTIDO,
	A_MIN				TIMESTAMP CONSTRAINT FK_SE_ANOTA_GOL
								  REFERENCES GOL
);

CREATE TABLE CONVOCADO (
	C_JUGADOR			INTEGER CONSTRAINT FK_CONVOCADO_JUGADOR
								REFERENCES JUGADOR,
	C_PARTIDO			TIMESTAMP CONSTRAINT FK_CONVOCADO_PARTIDO,
	POSICION			VARCHAR(24) CONSTRAINT DOM_CONVOCADO_POSICION
						(POSICION IN ('DELANTERO PUNTA', 'DELANTERO IZQUIERDO', 
						'DELANTERO DERECHO', 'EXTREMO IZQUIERDO', 'EXTREMO DERECHO',
						'MEDIO CENTRO OFENSIVO', 'VOLANTE IZQUIERDO', 'VOLANTE DERECHO',
						'MEDIO CENTRO DEFENSIVO', 'MEDIO IZQUIERDO DEFENSIVO',
						'MEDIO DERECHO DEFENSIVO', 'LATERAL IZQUIERDO', 'LATERAL DERECHO',
						'DEFENSA MEDIO', 'PORTERO')),
	MIN_ENTRA			INTEGER,
	MIN_SALE			INTEGER
);


