DROP TABLE PERTENECE_A_LA;
DROP TABLE COMPITE_EN;
DROP TABLE CONVOCADO;
DROP TABLE SE_ANOTA;
DROP TABLE TECNICO;
DROP TABLE GOL;
DROP TABLE AMONESTA;
DROP TABLE A_NACIONALIDAD;
DROP TABLE ARBITRO;
DROP TABLE J_NACIONALIDAD;
DROP TABLE JUGADOR;
DROP TABLE PARTIDO;
DROP TABLE EQUIPO;
DROP TABLE ORGANIZADOR;
DROP TABLE TEMPORADA;
DROP TABLE LIGA;
DROP TABLE COPA;
DROP TABLE COMPETENCIA;

CREATE TABLE COMPETENCIA (
	NOMBRE 				VARCHAR(40) CONSTRAINT PK_COMPETENCIA PRIMARY KEY,
	TROFEO				VARCHAR(40)

);

CREATE TABLE LIGA (
	C_NOMBRE			VARCHAR(40) CONSTRAINT PK_LIGA PRIMARY KEY,
	CONSTRAINT	FK_LIGA_COMPETENCIA FOREIGN KEY (C_NOMBRE) 
									REFERENCES COMPETENCIA
);

CREATE TABLE COPA (
	C_NOMBRE 			VARCHAR(40) CONSTRAINT PK_COPA PRIMARY KEY,
	CONSTRAINT	FK_LIGA_COMPETENCIA FOREIGN KEY (C_NOMBRE) 
									REFERENCES COMPETENCIA
);

CREATE TABLE ORGANIZADOR (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_ORGANIZADOR_COMPETENCIA
									REFERENCES COMPETENCIA,
	ORGANIZADOR 		VARCHAR(40) CONSTRAINT PK_ORGANIZADOR PRIMARY KEY
);

CREATE TABLE TEMPORADA (
	AÑO					INTEGER CONSTRAINT PK_TEMPORADA PRIMARY KEY,
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_TEMPORADA_COMPETENCIA
									REFERENCES COMPETENCIA
);

CREATE TABLE EQUIPO(
	NOMBRE				VARCHAR(40) CONSTRAINT PK_EQUIPO PRIMARY KEY,
	FUNDACION			TIMESTAMP,
	PAIS				VARCHAR(20),
	CIUDAD				VARCHAR(20),
	CAPACIDAD_ESTADIO	INTEGER CONSTRAINT DOM_EQUIPO_CAPACIDAD_ESTADIO 
								CHECK (CAPACIDAD_ESTADIO>0),
	NOMBRE_ESTADIO		VARCHAR(40),
	P_COMPETENCIA		VARCHAR(40) CONSTRAINT FK_EQUIPO_COMPETENCIA 
									REFERENCES COMPETENCIA
);

CREATE TABLE PARTIDO (
	FECHA				DATE CONSTRAINT PK_PARTIDO PRIMARY KEY,
	ASISTENCIA			INTEGER,
	MARCADOR			POINT,
	DURACION			INTEGER,
	LOCAL				VARCHAR(40) CONSTRAINT FK_PARTIDO_EQUIPO
								REFERENCES EQUIPO,
	VISITANTE			VARCHAR(40) CONSTRAINT FK_PARTIDO_EQUIPO01
								REFERENCES EQUIPO,
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_PARTIDO_COMPETENCIA
								REFERENCES COMPETENCIA,
	J_TEMPORADA			INTEGER CONSTRAINT FK_PARTIDO_TEMPORADA
								REFERENCES TEMPORADA
);

CREATE TABLE JUGADOR(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER	CONSTRAINT PK_JUGADOR PRIMARY KEY,
	NACIMIENTO			TIMESTAMP,
	PIE_HABIL			VARCHAR(9) CONSTRAINT DOM_JUGADOR_PIE_HABIL CHECK
						(PIE_HABIL IN ('IZQUIERDO, DERECHO')),
	ESTATURA			REAL,
	PESO				REAL,
	CJ_EQUIPO			VARCHAR(40) CONSTRAINT FK_JUGADOR_TECNICO
									REFERENCES EQUIPO,
	CJ_CLAUSULA_RECE	INTEGER,
	CJ_SALARIO			INTEGER,
	CJ_FINALIZACION		DATE,
	CJ_INICIO 			DATE,
	CONSTRAINT EXP_JUGADOR CHECK (CJ_FINALIZACION > CJ_INICIO)
	);

CREATE TABLE J_NACIONALIDAD (
	FIFA_ID				INTEGER CONSTRAINT FK_J_NACIONALIDAD_JUGADOR
								REFERENCES JUGADOR,
	NACIONALIDAD 		VARCHAR(40) CONSTRAINT PK_J_NACIONALIDAD PRIMARY KEY
);

CREATE TABLE ARBITRO (
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER CONSTRAINT PK_ARBITRO PRIMARY KEY
);

CREATE TABLE A_NACIONALIDAD (
	FIFA_ID				INTEGER CONSTRAINT FK_A_NACIONALIDAD_ARBITRO
								REFERENCES ARBITRO,
	NACIONALIDAD 		VARCHAR(40) CONSTRAINT PK_A_NACIONALIDAD PRIMARY KEY
);

CREATE TABLE AMONESTA (
	MIN 				NUMERIC(2,0),
	AMARILLA			BOOLEAN,
	ROJO				BOOLEAN,
	A_JUGADOR			INTEGER CONSTRAINT FK_AMONESTA_JUGADOR
								REFERENCES JUGADOR,
	A_PARTIDO 			DATE CONSTRAINT FK_AMONESTA_PARTIDO
							  REFERENCES PARTIDO,
	A_ARBITRO			INTEGER CONSTRAINT FK_AMONESTA_ARBITRO
							  	REFERENCES ARBITRO
);

CREATE TABLE GOL(
	MIN					NUMERIC(2,0) CONSTRAINT PK_GOL PRIMARY KEY,
	TIPO 				VARCHAR(13) CONSTRAINT DOM_GOL_TIPO CHECK
						(TIPO IN ('TIRO LIBRE', 'PENAL', 'AUTOGOL', 'CABEZASO', 
							'PIE IZQUIERDO', 'PIE DERECHO')),
	EN_PARTIDO 			DATE CONSTRAINT FK_GOL_PARTIDO
								  REFERENCES PARTIDO,
	ASISTE				INTEGER CONSTRAINT FK_GOL_JUGADOR
								REFERENCES JUGADOR,
	ANOTA 				INTEGER	CONSTRAINT FK_GOL_JUGADOR01
								REFERENCES JUGADOR,
	CONSTRAINT EXP_GOL CHECK (ASISTE != ANOTA)
);

CREATE TABLE TECNICO(
	NOMBRE 				VARCHAR(40),
	FIFA_ID				INTEGER CONSTRAINT PK_TECNICO PRIMARY KEY,
	CT_EQUIPO			VARCHAR(40)	CONSTRAINT FK_TECNICO_EQUIPO
									REFERENCES EQUIPO,
	CT_FINALIZACION		DATE,
	CT_INICIO 			DATE,
	CONSTRAINT EXP_TECNICO CHECK (CT_FINALIZACION > CT_INICIO)
);

CREATE TABLE SE_ANOTA (
	A_PARTIDO 			DATE CONSTRAINT FK_SE_ANOTA_PARTIDO
							REFERENCES PARTIDO,
	A_MIN				NUMERIC(2,0) CONSTRAINT FK_SE_ANOTA_GOL
								  	REFERENCES GOL
);

CREATE TABLE CONVOCADO (
	C_JUGADOR			INTEGER CONSTRAINT FK_CONVOCADO_JUGADOR
								REFERENCES JUGADOR,
	C_PARTIDO			DATE CONSTRAINT FK_CONVOCADO_PARTIDO
								REFERENCES PARTIDO,
	MIN_ENTRA			INTEGER,
	MIN_SALE			INTEGER,
	CONSTRAINT EXP_CONVOCADO CHECK (MIN_ENTRA < MIN_SALE),
	POSICION			VARCHAR(24) CONSTRAINT DOM_CONVOCADO_POSICION CHECK
						(POSICION IN ('DELANTERO PUNTA', 'DELANTERO IZQUIERDO', 
						'DELANTERO DERECHO', 'EXTREMO IZQUIERDO', 'EXTREMO DERECHO',
						'MEDIO CENTRO OFENSIVO', 'VOLANTE IZQUIERDO', 'VOLANTE DERECHO',
						'MEDIO CENTRO DEFENSIVO', 'MEDIO IZQUIERDO DEFENSIVO',
						'MEDIO DERECHO DEFENSIVO', 'LATERAL IZQUIERDO', 'LATERAL DERECHO',
						'DEFENSA MEDIO', 'PORTERO'))

);

CREATE TABLE PERTENECE_A_LA (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_PERTENECE_COMPETENCIA
									REFERENCES COMPETENCIA,
	PARTIDO 			DATE CONSTRAINT FK_PERTENECE_PARTIDO
								REFERENCES PARTIDO,
	JORNADA				INTEGER,
	FASE				VARCHAR(17) CONSTRAINT DOM_PERTENECE_FASE CHECK
						(FASE IN ('FASE ELIMINATORIA', '32AVOS DE FINAL','16AVO DE FINAL', 
							'8AVO DE FINAL', '4TOS DE FINAL', 'SEMI-FINAL', 'FINAL'))
);
 
CREATE TABLE COMPITE_EN (
	C_NOMBRE			VARCHAR(40) CONSTRAINT FK_COMPITE_COMPETENCIA
									REFERENCES COMPETENCIA,
	E_NOMBRE			VARCHAR(40) CONSTRAINT FK_COMPITE_EQUIPO
									REFERENCES EQUIPO
);