/* ESTE SCRIPT CREA LAS RESTRICCIONES DE LA BASE DE DATOS
 * BASE DE DATOS EN MODELO RELACIONAL
 * AUTOR: JOSE PEÑA #11-10775 Y DANIELA SOCAS #11-10979
 */

/* RESTRICCIONES DE COMPETENCIA */
ALTER TABLE COMPETENCIA ADD CONSTRAINT PK_COMPETENCIA PRIMARY KEY (NOMBRE);

/* RESTRICCIONES DE LIGA */
ALTER TABLE LIGA ADD CONSTRAINT PK_LIGA PRIMARY KEY (C_NOMBRE);
ALTER TABLE LIGA ADD CONSTRAINT FK_LIGA_COMPETENCIA 
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);

/* RESTRICCIONES DE COPA */
ALTER TABLE COPA ADD CONSTRAINT PK_COPA PRIMARY KEY (C_NOMBRE);
ALTER TABLE COPA ADD CONSTRAINT FK_COPA_COMPETENCIA 
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);

/* RESTRICCIONES DE ORGANIZADOR */
ALTER TABLE ORGANIZADOR ADD CONSTRAINT FK_ORGANIZADOR_COMPETENCIA 
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);
ALTER TABLE ORGANIZADOR ADD CONSTRAINT PK_ORGANIZADOR 
PRIMARY KEY (ORGANIZADOR);

/* RESTRICCIONES DE TEMPORADA */
ALTER TABLE TEMPORADA ADD CONSTRAINT PK_TEMPORADA 
PRIMARY KEY (AÑO);
ALTER TABLE TEMPORADA ADD CONSTRAINT FK_TEMPORADA_COMPETENCIA 
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);

/* RESTRICCIONES DE EQUIPO */
ALTER TABLE EQUIPO ADD CONSTRAINT PK_EQUIPO PRIMARY KEY (NOMBRE);
ALTER TABLE EQUIPO ADD CONSTRAINT DOM_EQUIPO_CAPACIDAD_ESTADIO CHECK
(CAPACIDAD_ESTADIO > 0);
ALTER TABLE EQUIPO ADD CONSTRAINT FK_EQUIPO_COMPETENCIA
FOREIGN KEY (P_COMPETENCIA) REFERENCES COMPETENCIA(NOMBRE);

/* RESTRICCIONES DE PARTIDO */
ALTER TABLE PARTIDO ADD CONSTRAINT PK_PARTIDO 
PRIMARY KEY(FECHA);
ALTER TABLE PARTIDO ADD CONSTRAINT DOM_PARTIDO_ASISTENCIA CHECK
(ASISTENCIA>=0);
ALTER TABLE PARTIDO ADD CONSTRAINT DOM_PARTIDO_DURACION CHECK
(DURACION>0);
ALTER TABLE PARTIDO ADD CONSTRAINT FK_PARTIDO_EQUIPO
FOREIGN KEY (LOCAL) REFERENCES EQUIPO(NOMBRE);
ALTER TABLE PARTIDO ADD CONSTRAINT FK_PARTIDO_EQUIPO01 
FOREIGN KEY (VISITANTE) REFERENCES EQUIPO(NOMBRE);
ALTER TABLE PARTIDO ADD CONSTRAINT FK_PARTIDO_COMPETENCIA
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);
ALTER TABLE PARTIDO ADD CONSTRAINT FK_PARTIDO_TEMPORADA
FOREIGN KEY (J_TEMPORADA) REFERENCES TEMPORADA(AÑO);
ALTER TABLE PARTIDO ADD CONSTRAINT EXP_PARTIDO CHECK
(LOCAL != VISITANTE);

/* RESTRICCIONES DE JUGADOR */
ALTER TABLE JUGADOR ADD CONSTRAINT PK_JUGADOR PRIMARY KEY (FIFA_ID);
ALTER TABLE JUGADOR ADD CONSTRAINT DOM_JUGADOR_PIE_HABIL CHECK
(PIE_HABIL IN ('IZQUIERDO, DERECHO'));
ALTER TABLE JUGADOR ADD CONSTRAINT DOM_JUGADOR_ESTATURA CHECK
(ESTATURA > 0);
ALTER TABLE JUGADOR ADD CONSTRAINT DOM_JUGADOR_PESO CHECK
(ESTATURA > 0);
ALTER TABLE JUGADOR ADD CONSTRAINT FK_JUGADOR_EQUIPO 
FOREIGN KEY (CJ_EQUIPO) REFERENCES EQUIPO(NOMBRE);
ALTER TABLE JUGADOR ADD CONSTRAINT EXP_JUGADOR CHECK
(CJ_FINALIZACION > CJ_INICIO);

/* RESTRICCIONES DE NACIONALIDAD DEL JUGADOR */
ALTER TABLE J_NACIONALIDAD ADD CONSTRAINT FK_J_NACIONALIDAD_JUGADOR
FOREIGN KEY (FIFA_ID) REFERENCES JUGADOR(FIFA_ID);
ALTER TABLE J_NACIONALIDAD ADD CONSTRAINT PK_J_NACIONALIDAD 
PRIMARY KEY (NACIONALIDAD);

/* RESTRICCIONES DE ARBITRO */
ALTER TABLE ARBITRO	ADD CONSTRAINT PK_ARBITRO PRIMARY KEY (FIFA_ID);

/* RESTRICCIONES DE NACIONALIDAD DEL ARBITRO */
ALTER TABLE A_NACIONALIDAD ADD CONSTRAINT FK_A_NACIONALIDAD_ARBITRO
FOREIGN KEY (FIFA_ID) REFERENCES ARBITRO(FIFA_ID);
ALTER TABLE A_NACIONALIDAD ADD CONSTRAINT PK_A_NACIONALIDAD
PRIMARY KEY (NACIONALIDAD);

/* RESTRICCIONES DE AMONESTA */
ALTER TABLE AMONESTA ADD CONSTRAINT FK_AMONESTA_JUGADOR
FOREIGN KEY (A_JUGADOR) REFERENCES JUGADOR(FIFA_ID);
ALTER TABLE AMONESTA ADD CONSTRAINT FK_AMONESTA_PARTIDO
FOREIGN KEY (A_PARTIDO) REFERENCES PARTIDO(FECHA);
ALTER TABLE AMONESTA ADD CONSTRAINT FK_AMONESTA_ARBITRO
FOREIGN KEY (A_ARBITRO) REFERENCES ARBITRO(FIFA_ID);
ALTER TABLE AMONESTA ADD CONSTRAINT EXP_AMONESTA CHECK
(AMARILLA != ROJA);

/* RESTRICCIONES DE GOL */
ALTER TABLE GOL ADD CONSTRAINT PK_GOL 
PRIMARY KEY (MIN);
ALTER TABLE GOL ADD CONSTRAINT DOM_GOL_TIPO CHECK
(TIPO IN ('TIRO LIBRE', 'PENAL', 'AUTOGOL', 'CABEZASO', 
'PIE IZQUIERDO', 'PIE DERECHO'));
ALTER TABLE GOL ADD CONSTRAINT FK_GOL_PARTIDO
FOREIGN KEY (EN_PARTIDO) REFERENCES PARTIDO(FECHA);
ALTER TABLE GOL ADD CONSTRAINT FK_GOL_JUGADOR
FOREIGN KEY	(ASISTE) REFERENCES JUGADOR(FIFA_ID);
ALTER TABLE GOL ADD CONSTRAINT FK_GOL_JUGADOR01
FOREIGN KEY (ANOTA) REFERENCES JUGADOR(FIFA_ID);
ALTER TABLE GOL ADD CONSTRAINT EXP_GOL CHECK
(ASISTE != ANOTA);

/* RESTRICCIONES DE TECNICO */
ALTER TABLE TECNICO ADD CONSTRAINT PK_TECNICO PRIMARY KEY (FIFA_ID);
ALTER TABLE TECNICO ADD CONSTRAINT FK_TECNICO_EQUIPO
FOREIGN KEY (CT_EQUIPO) REFERENCES EQUIPO(NOMBRE);
ALTER TABLE TECNICO ADD CONSTRAINT EXP_TECNICO CHECK 
(CT_FINALIZACION > CT_INICIO);


/* RESTRICCIONES DE SE_ANOTA */
ALTER TABLE SE_ANOTA ADD CONSTRAINT FK_SE_ANOTA_PARTIDO
FOREIGN KEY (A_PARTIDO) REFERENCES PARTIDO(FECHA);
ALTER TABLE SE_ANOTA ADD CONSTRAINT FK_SE_ANOTA_GOL
FOREIGN KEY (A_MIN) REFERENCES GOL(MIN);


/* RESTRICCIONES DE CONVOCADO */
ALTER TABLE CONVOCADO ADD CONSTRAINT FK_CONVOCADO_JUGADOR
FOREIGN KEY (C_JUGADOR) REFERENCES JUGADOR(FIFA_ID);
ALTER TABLE CONVOCADO ADD CONSTRAINT FK_CONVOCADO_PARTIDO
FOREIGN KEY	(C_PARTIDO) REFERENCES PARTIDO(FECHA);
ALTER TABLE CONVOCADO ADD CONSTRAINT EXP_CONVOCADO CHECK
(MIN_ENTRA < MIN_SALE);
ALTER TABLE CONVOCADO ADD CONSTRAINT DOM_CONVOCADO_POSICION CHECK
(POSICION IN ('DELANTERO PUNTA', 'DELANTERO IZQUIERDO', 
'DELANTERO DERECHO', 'EXTREMO IZQUIERDO', 'EXTREMO DERECHO',
'MEDIO CENTRO OFENSIVO', 'VOLANTE IZQUIERDO', 'VOLANTE DERECHO',
'MEDIO CENTRO DEFENSIVO', 'MEDIO IZQUIERDO DEFENSIVO',
'MEDIO DERECHO DEFENSIVO', 'LATERAL IZQUIERDO', 'LATERAL DERECHO',
'DEFENSA MEDIO', 'PORTERO'));


/* RESTRICCIONES DE PERTENECE_A_LA */
ALTER TABLE PERTENECE_A_LA ADD CONSTRAINT FK_PERTENECE_COMPETENCIA
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);
ALTER TABLE PERTENECE_A_LA ADD CONSTRAINT FK_PERTENECE_PARTIDO
FOREIGN KEY (PARTIDO) REFERENCES PARTIDO(FECHA);
ALTER TABLE PERTENECE_A_LA ADD CONSTRAINT DOM_PERTENECE_JORNADA CHECK
(JORNADA > 0);
ALTER TABLE PERTENECE_A_LA ADD CONSTRAINT DOM_PERTENECE_FASE CHECK
(FASE IN ('FASE ELIMINATORIA', '32AVOS DE FINAL','16AVO DE FINAL', 
'8AVO DE FINAL', '4TOS DE FINAL', 'SEMI-FINAL', 'FINAL'));

/* RESTRICCIONES DE COMPITE_EN */
ALTER TABLE COMPITE_EN ADD CONSTRAINT FK_COMPITE_COMPETENCIA
FOREIGN KEY (C_NOMBRE) REFERENCES COMPETENCIA(NOMBRE);
ALTER TABLE COMPITE_EN ADD CONSTRAINT FK_COMPITE_EQUIPO
FOREIGN KEY (E_NOMBRE) REFERENCES EQUIPO(NOMBRE);











